### ISSUE TITLE
Update the flatpak locale to GNOME40

### ISSUE THREAD

**Issue by VarLad** [flathub/com.github.alexhuntley.Plots#1]
The current platform locale is at 3.38
It'd be nice if you could update it to 40

**Comment by alexhuntley** [comment]
Plots is currently using GTK 3 for its widgets, so would there be any benefit to this?

**Comment by VarLad** [comment]
Users wouldn't have to download the 3.38 runtime that way
A lot of flatpak softwares have shifted to GNOME40/GNOME41, Plots is kinda the only software for which I need the 3.8 workspace

If possible, using GNOME40/GNOME41 would be nice

**Comment by alexhuntley** [comment]
OK, I wasn't aware of this. Do you know if GTK 3 apps can still run on the 40 runtime?

If so I'll try to migrate to it for the next release.

**Comment by alexhuntley** [comment]
Fixed in 2e7efb1
